import { useEffect, useState } from 'react'
import { Pencil, Reply, Trash2 } from 'lucide-react'
import { useAuth } from '../../hooks/useAuth'
import { createComment, deleteComment, listComments, updateComment } from '../../services/comments'
import { Button } from '../ui/Button'
import { Textarea } from '../ui/Textarea'
import { useToast } from '../ui/Toast'
export function CommentList({ reviewId }) { const { user } = useAuth(); const toast = useToast(); const [comments, setComments] = useState([]); const [content, setContent] = useState(''); const [replyTo, setReplyTo] = useState(null); const load = async () => { const { data, error } = await listComments(reviewId); if (!error) setComments(data || []) }; useEffect(() => { load() }, [reviewId]); const submit = async (event) => { event.preventDefault(); if (!user) return toast('댓글을 쓰려면 로그인해주세요.', 'error'); if (!content.trim()) return; const { error } = await createComment({ review_id: reviewId, user_id: user.id, parent_id: replyTo?.id || null, content: content.trim() }); if (error) toast(error.message, 'error'); else { setContent(''); setReplyTo(null); load() } }; const remove = async (id) => { if (!window.confirm('댓글을 삭제할까요?')) return; const { error } = await deleteComment(id); if (error) toast(error.message, 'error'); else load() }; const edit = async (comment) => { const next = window.prompt('댓글을 수정하세요.', comment.content); if (!next?.trim()) return; const { error } = await updateComment(comment.id, next.trim()); if (error) toast(error.message, 'error'); else load() }; const roots = comments.filter((comment) => !comment.parent_id); return <div className="mt-5 space-y-3 border-t pt-4">{roots.map((comment) => <div key={comment.id} className="space-y-2"><CommentItem comment={comment} own={comment.user_id === user?.id} onReply={() => setReplyTo(comment)} onEdit={() => edit(comment)} onDelete={() => remove(comment.id)}/>{comments.filter((item) => item.parent_id === comment.id).map((reply) => <CommentItem key={reply.id} comment={reply} own={reply.user_id === user?.id} reply onEdit={() => edit(reply)} onDelete={() => remove(reply.id)}/>)}</div>)}<form onSubmit={submit} className="pt-2"><p className="mb-2 text-xs text-slate-500">{replyTo ? `${replyTo.profiles?.nickname || '사용자'}님에게 답글 작성 중` : '댓글을 남겨보세요.'}</p><div className="flex gap-2"><Textarea value={content} onChange={(event) => setContent(event.target.value)} className="min-h-11 flex-1" placeholder="댓글을 입력하세요."/><Button type="submit" className="self-end">등록</Button></div></form></div> }
function CommentItem({ comment, own, reply, onReply, onEdit, onDelete }) { return <div className={`rounded-xl bg-stone-50 p-3 text-sm ${reply ? 'ml-5 border-l-2 border-amber-300' : ''}`}><div className="flex justify-between gap-2"><span className="font-bold">{comment.profiles?.nickname || '사용자'}</span><div className="flex gap-1">{!reply && <button aria-label="답글" onClick={onReply} className="p-1 text-slate-500 hover:text-red-700"><Reply size={15}/></button>}{own && <><button aria-label="댓글 수정" onClick={onEdit} className="p-1 text-slate-500"><Pencil size={15}/></button><button aria-label="댓글 삭제" onClick={onDelete} className="p-1 text-red-700"><Trash2 size={15}/></button></>}</div></div><p className="mt-1 whitespace-pre-wrap text-slate-700">{comment.content}</p></div> }
