import { Heart, MessageCircle, Pencil, Star, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../../hooks/useAuth'
import { deleteReview } from '../../services/reviews'
import { toggleLike } from '../../services/likes'
import { formatDate } from '../../lib/utils'
import { CommentList } from '../comment/CommentList'
import { useToast } from '../ui/Toast'
export function ReviewCard({ review, onChanged }) { const { user } = useAuth(); const toast = useToast(); const navigate = useNavigate(); const liked = review.review_likes?.some((like) => like.user_id === user?.id); const likes = review.review_likes?.length || 0; const own = review.user_id === user?.id; const remove = async () => { if (!window.confirm('이 리뷰를 삭제할까요? 댓글과 좋아요도 함께 삭제됩니다.')) return; const { error } = await deleteReview(review.id); if (error) return toast(error.message, 'error'); toast('리뷰를 삭제했습니다.'); onChanged() }; const like = async () => { if (!user) return navigate('/login'); const { error } = await toggleLike(review.id, user.id, liked); if (error) toast(error.message, 'error'); else onChanged() }; return <article className="surface p-5"><div className="flex items-start justify-between gap-4"><div><Link to={`/profile/${review.user_id}`} className="font-bold hover:text-red-700">{review.profiles?.nickname || '알 수 없는 사용자'}</Link><p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><span className="inline-flex items-center gap-1 font-semibold text-slate-700"><Star size={15} className="fill-amber-400 text-amber-500"/>{Number(review.rating).toFixed(1)}</span>{formatDate(review.created_at)}</p></div>{own && <div className="flex gap-1"><Link aria-label="리뷰 수정" className="grid size-10 place-items-center rounded-lg hover:bg-stone-100" to={`/reviews/${review.id}/edit`}><Pencil size={17}/></Link><button aria-label="리뷰 삭제" onClick={remove} className="grid size-10 place-items-center rounded-lg text-red-700 hover:bg-red-50"><Trash2 size={17}/></button></div>}</div><h3 className="mt-4 font-bold">{review.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{review.content}</p><div className="mt-4 flex items-center gap-2 border-t pt-3"><button onClick={like} className={`inline-flex min-h-10 items-center gap-1 rounded-lg px-2 text-sm font-semibold ${liked ? 'text-red-700' : 'text-slate-600 hover:bg-stone-100'}`}><Heart size={18} className={liked ? 'fill-red-600' : ''}/>좋아요 {likes}</button><span className="inline-flex items-center gap-1 text-sm text-slate-500"><MessageCircle size={17}/>댓글</span></div><CommentList reviewId={review.id}/></article> }
